#### this file is used for learning data type conversion between pytorch and numpy

In [11]:
import numpy as np
import torch as torch

# converting torch tensor to numpy array.
a_tensor = torch.tensor([[[1, 2, 3]]])
a = a_tensor.numpy()
print(a.shape)

# converting numpy array to torch tensor
# be careful this from numpy method is shadow copy.
a = np.full((3, 3, 5), 5.0, dtype=np.float32)
c = torch.from_numpy(a)
c[0,0,0]=10.0
print("shadow copy from_numpy a:")
print(a)
print("shadow copy form_numpy c:")
print(c)

# deep copy from numpy to tensor
d = torch.tensor(a)
d[0, 0, 0] = -1.0
# print("deep copy a:")
# print(a)
# print("deep copy d:")
# print(d)

# shadow copy from numpy to tensor
a[0, 0, 0] = 5.0
e = torch.as_tensor(a)
e[0, 0, 0] = 1.0
# print("shadow copy a:")
# print(a)
# print("shadow copy e:")
# print(e)


(1, 1, 3)
deep copy from_numpy a:
[[[10.  5.  5.  5.  5.]
  [ 5.  5.  5.  5.  5.]
  [ 5.  5.  5.  5.  5.]]

 [[ 5.  5.  5.  5.  5.]
  [ 5.  5.  5.  5.  5.]
  [ 5.  5.  5.  5.  5.]]

 [[ 5.  5.  5.  5.  5.]
  [ 5.  5.  5.  5.  5.]
  [ 5.  5.  5.  5.  5.]]]
deep copy form_numpy c:
tensor([[[10.,  5.,  5.,  5.,  5.],
         [ 5.,  5.,  5.,  5.,  5.],
         [ 5.,  5.,  5.,  5.,  5.]],

        [[ 5.,  5.,  5.,  5.,  5.],
         [ 5.,  5.,  5.,  5.,  5.],
         [ 5.,  5.,  5.,  5.,  5.]],

        [[ 5.,  5.,  5.,  5.,  5.],
         [ 5.,  5.,  5.,  5.,  5.],
         [ 5.,  5.,  5.,  5.,  5.]]])
