In [15]:
import numpy as np
from scipy import linalg

# matrix determinant
a = np.array([[1, 5, 6], [2, 4, 1], [2, 5, 1]], dtype=np.int32)
b = linalg.det(a)
print(b)

# matrix inverse
b = linalg.inv(a)
print(b)

# matrix solver
z = np.array([5, 2, 1])
print(linalg.solve(a, z))

# eigen values and eigen functions
eigen_value, eigen_vector = linalg.eig(a)
print(eigen_value)
print(eigen_vector)

# matrix multiply.
print(a @ b)

# many more about optimize and solve module...


10.999999999999993
[[-0.09090909  2.27272727 -1.72727273]
 [ 0.         -1.          1.        ]
 [ 0.18181818  0.45454545 -0.54545455]]
[ 2.36363636 -1.          1.27272727]
[ 8.32182538+0.j -1.32182538+0.j -1.        +0.j]
[[-7.29352613e-01 -9.37902146e-01  9.28476691e-01]
 [-4.55609116e-01  3.37053835e-01 -3.71390676e-01]
 [-5.10357815e-01  8.20626387e-02 -6.08513425e-16]]
[[ 1.00000000e+00  4.44089210e-16 -6.66133815e-16]
 [ 1.66533454e-16  1.00000000e+00 -5.55111512e-16]
 [ 1.66533454e-16  4.44089210e-16  1.00000000e+00]]
