In [41]:
import numpy as np

# create a zero tensor with dims=(2,5,6) and data type = float.
a = np.zeros((2, 5, 6), dtype=np.float32)

# create a identity matrix with 8 rows and 8 columns,
# data type = int8
b = np.identity(8, dtype=np.int8)

# create a full matrix with all -1.0
c = np.full((5, 8), -1.0, dtype=np.float32)

# create a identity matrix
# this method is actually same as np.identity
d = np.eye(5)
print(d)

# create a tensor with pre-defined values.
e = np.array([[5, 6, 2, 4], [4, 84, 5, 6]], dtype=np.int64)
print(e)

# create a full_like tensor
f = np.full_like(e, 2.0)
print(f)

# vertically stacking tensors
g = np.vstack([e, f])
print(g)

# horizontally stacking tensors
h = np.hstack([e, f])

# replacing items
h[:, 1::2] = np.array([[8, 8, 8, 8], [9, 9, 9, 9]])

# shalow copy
i = h[:, 0::2]
print(i)

# deep copy
j = h[:, 0::2].copy()
print(j)

# indexing
num = j[0, 2]

# reshaping
j = j.reshape(4, 2)
print(j)

# min
min_value = np.min(j)
print(min_value)

# max
max_value = np.max(j)
print(max_value)

# determinat
print(np.linalg.det(d))

# min value per row
print(np.min(j, axis=1))

# min value per column
print(np.min(j, axis=0))

# element-wise product-hadamad product
a = np.array([1, 2, 3], dtype=np.float32)
b = np.array([4, 5, 6], dtype=np.float32)
c = a*b
print(c)

# l2 norm
print(np.linalg.norm(a))

# cross product.
c = np.cross(a, b)
print(c)

# dot product
print(np.dot(a, b))

# exponential
a = a**2
print(a)

# mod operation in numpy
c = np.mod(b, a)
print(c)

# matrix multiply.
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[0, 1], [5, 5], [8, 1]])
c = np.matmul(a, b)
print(c)

# matrix inverse
a = np.array([[1, 5, 6], [2, 7, 10], [0, 5, 3]])
b = np.linalg.inv(a)
print(b)

# matrix transpose
b=a.T
print(b)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[ 5  6  2  4]
 [ 4 84  5  6]]
[[2 2 2 2]
 [2 2 2 2]]
[[ 5  6  2  4]
 [ 4 84  5  6]
 [ 2  2  2  2]
 [ 2  2  2  2]]
[[5 2 2 2]
 [4 5 2 2]]
[[5 2 2 2]
 [4 5 2 2]]
[[5 2]
 [2 2]
 [4 5]
 [2 2]]
2
5
1.0
[2 2 4 2]
[2 2]
[ 4. 10. 18.]
3.7416575
[-3.  6. -3.]
32.0
[1. 4. 9.]
[0. 1. 6.]
[[34 14]
 [73 35]]
[[-29.  15.   8.]
 [ -6.   3.   2.]
 [ 10.  -5.  -3.]]
[[ 1  2  0]
 [ 5  7  5]
 [ 6 10  3]]
